### ISSUE TITLE
you should add sensitive true to the file_create call

### ISSUE THREAD

**Issue by jchauncey** [onddo/ssl_certificate-cookbook#12]
Right now you print out the certs by default and this could dangerous if you are retrieving certs from a data bag. 

https://github.com/onddo/ssl_certificate-cookbook/blob/master/libraries/provider_ssl_certificate.rb#L56

**Comment by zuazo** [comment]
@jchauncey, thanks for reporting. Fixed in master.

**Comment by zuazo** [comment]
Released in [1.5.0](https://github.com/onddo/ssl_certificate-cookbook/releases/tag/1.5.0).
