### ISSUE TITLE
SANs should support IPs

### ISSUE THREAD

**Issue by jchauncey** [onddo/ssl_certificate-cookbook#13]
When creating our certs they need to also contain a SAN with the ip of the host. Right now this does not occur because the provider only supports DNS entries. 
It should look like the following:
```
[ alt_names ]
#
IP.1 = 192.168.1.100
IP.2 = 127.0.0.1
```

**Comment by zuazo** [comment]
Hi @jchauncey,

This has been implemented in master. Thanks for reporting!

**Comment by zuazo** [comment]
Released in [1.5.0](https://github.com/onddo/ssl_certificate-cookbook/releases/tag/1.5.0).
